# Streamlit secrets file
# Copy this to .streamlit/secrets.toml for cloud deployment

[secrets]
password = "STS2025Dashboard!"  # Change this password
admin_email = "your.email@delta.com"

# For production deployment, also add:
# [database]
# connection_string = "your_db_connection_if_needed"
